<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <EnablePackageVersionOverride>false</EnablePackageVersionOverride>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup Label="Microsoft">
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0"  />
  </ItemGroup>

  <ItemGroup Label="Code Quality">
    <PackageVersion Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.14.15"/>
  </ItemGroup>

  <ItemGroup Label="Microsoft Tests">
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>

  <ItemGroup Label="Tests">
    <PackageVersion Include="xunit" Version="2.9.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageVersion Include="AutoFixture" Version="4.18.1" />
    <PackageVersion Include="FluentAssertions" Version="6.12.2" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
  </ItemGroup>

  <ItemGroup Label="Other libs">
    <PackageVersion Include="FluentValidation" Version="11.10.0" />
  </ItemGroup>
</Project>
