<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>EffectiveResult</PackageId>
        <Description>
          Implementation of the result monad pattern for an alternative way of handling errors.
        </Description>
        <Authors>Nickolay Sikachin</Authors>
        <Copyright>Copyright © Nickolay Sikachin 2025</Copyright>

        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/EnergyNick/EffectiveResult</PackageProjectUrl>

        <PackageVersion>1.1.1</PackageVersion>
        <PackageIcon>icon-128.png</PackageIcon>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageReleaseNotes>
          Add append method with condition for ResultBuilder, add error constructor from enumerable
        </PackageReleaseNotes>
        <PackageTags>Result Monad Functional Pattern Error Handling Exception</PackageTags>
    </PropertyGroup>

    <PropertyGroup>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All"/>

        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
          <_Parameter1>EffectiveResult.Tests</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\README.md" Pack="true" PackagePath="\"/>
        <None Include="..\..\icons\icon-128.png" Pack="true" PackagePath="\"/>
    </ItemGroup>

</Project>
